<?php

use Illuminate\Database\Seeder;
use Database\TruncateTable;
use Database\DisableForeignKeys;

class WfDefinitionsTableSeeder extends Seeder
{

    use DisableForeignKeys, TruncateTable;
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        $this->disableForeignKeys('wf_definitions');
        $this->delete('wf_definitions');

        \DB::table('wf_definitions')->insert(array (
            /*START TAF*/
            0 =>
            array (
                'id' => 1,
                'level' => '1',
                'unit_id' => 33,
                'designation_id' => 63,
                'description' => 'Apply TAF',
                'msg_next' => 'Request report verification',
                'wf_module_id' => '1',
                'active' => '1',
                'allow_rejection' => 1,
                'allow_repeat_participate' => 0,
                'created_at' => '2020-07-08 20:16:49',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'is_approval' => 0,
                'has_next_start_optional' => 0,
                'is_optional' => 0,
                'can_close' => 0,
                'action_description' => 'Applied',
                'status_description' => 'Applied',
//                'assign_next_user' => 0,
            ),
            1 =>
            array (
                'id' => 2,
                'level' => '2',
                'unit_id' => '32',
                'designation_id' => '62',
                'description' => 'Verify TAF',
                'msg_next' => 'Request for endorsement',
                'wf_module_id' => '1',
                'active' => '1',
                'allow_rejection' => 1,
                'allow_repeat_participate' => 1,
                'created_at' => '2020-07-08 20:16:49',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'is_approval' => 0,
                'has_next_start_optional' => 0,
                'is_optional' => 0,
                'can_close' => 0,
                'action_description' => 'Verified',
                'status_description' => 'Verified',
//                'assign_next_user' => 0,
            ),
            2 =>
            array (
                'id' => 3,
                'level' => '3',
                'unit_id' => '6',
                'designation_id' => '9',
                'description' => 'Endorse TAF',
                'msg_next' => 'Request for Approval',
                'wf_module_id' => '1',
                'active' => '1',
                'allow_rejection' => 1,
                'allow_repeat_participate' => 0,
                'created_at' => '2020-07-08 20:16:49',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'is_approval' => 0,
                'has_next_start_optional' => 0,
                'is_optional' => 0,
                'can_close' => 0,
                'action_description' => 'Endorsed',
                'status_description' => 'Endorsed',
//                'assign_next_user' => 0,
            ),
            3 =>
            array (
                'id' => 4,
                'level' => '4',
                'unit_id' => '31',
                'designation_id' => '61',
                'description' => 'Approve TAF',
                'msg_next' => 'Request for inspection',
                'wf_module_id' => '1',
                'active' => '1',
                'allow_rejection' => 1,
                'allow_repeat_participate' => 1,
                'created_at' => '2020-07-08 20:16:49',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'is_approval' => 1,
                'has_next_start_optional' => 0,
                'is_optional' => 0,
                'can_close' => 0,
                'action_description' => 'Approved',
                'status_description' => 'Approved',
//                'assign_next_user' => 0,
            ),
            4 =>
                array (
                    'id' => 5,
                    'level' => '5',
                    'unit_id' => '1',
                    'designation_id' => '1',
                    'description' => 'Inspect TAF',
                    'msg_next' => 'Request for payment',
                    'wf_module_id' => '1',
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-07-08 20:16:49',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Inspected',
                    'status_description' => 'Inspected',
//                'assign_next_user' => 0,
                ),
            5 =>
                array (
                    'id' => 6,
                    'level' => '6',
                    'unit_id' => '1',
                    'designation_id' => '2',
                    'description' => 'Pay TAF',
                    'msg_next' => 'Request for payment',
                    'wf_module_id' => '1',
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-07-08 20:16:49',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 1,
                    'action_description' => 'Paid',
                    'status_description' => 'Paid',
//                'assign_next_user' => 0,
                ),
            /*END TAF*/
            /*START TBER*/
            6 =>
                array (
                    'id' => 7,
                    'level' => '1',
                    'unit_id' => 33,
                    'designation_id' => 63,
                    'description' => 'Request TBER',
                    'msg_next' => 'Request for verification',
                    'wf_module_id' => 2,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-09-22 11:35:56',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Requested',
                    'status_description' => 'Requested',
//                'assign_next_user' => 0,
                ),
            7 =>
                array (
                    'id' => 8,
                    'level' => '2',
                    'unit_id' => '32',
                    'designation_id' => '62',
                    'description' => 'Verify TBER',
                    'msg_next' => 'Request for endorsement',
                    'wf_module_id' => 2,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 1,
                    'created_at' => '2020-09-22 11:35:56',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Verified',
                    'status_description' => 'Verified',
//                'assign_next_user' => 0,
                ),
            8 =>
                array (
                    'id' => 9,
                    'level' => '3',
                    'unit_id' => '1',
                    'designation_id' => '1',
                    'description' => 'Review TBER',
                    'msg_next' => 'Request for Endorsement',
                    'wf_module_id' => 2,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-07-08 20:16:49',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Reviewed',
                    'status_description' => 'Reviewed',
//                'assign_next_user' => 0,
                ),
            9 =>
                array (
                    'id' => 10,
                    'level' => '4',
                    'unit_id' => '6',
                    'designation_id' => '9',
                    'description' => 'Endorse TBER',
                    'msg_next' => 'Request for Payment',
                    'wf_module_id' => 2,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-09-22 11:35:56',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 1,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Endorsed',
                    'status_description' => 'Endorsed',
//                'assign_next_user' => 0,
                ),
            10 =>
                array (
                    'id' => 11,
                    'level' => '5',
                    'unit_id' => '1',
                    'designation_id' => '2',
                    'description' => 'Pay TBER',
                    'msg_next' => 'Request for payment',
                    'wf_module_id' => '2',
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-09-22 11:35:56',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 1,
                    'action_description' => 'Paid',
                    'status_description' => 'Paid',
                ),
            /*END TBER*/

            /*START TAF EXTENSION*/
            11 =>
                array (
                    'id' => 12,
                    'level' => '1',
                    'unit_id' => 33,
                    'designation_id' => 63,
                    'description' => 'Apply TAF Extension',
                    'msg_next' => 'Request TAF Extension verification',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Applied',
                    'status_description' => 'Applied',
//                'assign_next_user' => 0,
                ),
            12 =>
                array (
                    'id' => 13,
                    'level' => '2',
                    'unit_id' => '32',
                    'designation_id' => '62',
                    'description' => 'Verify TAF Extension',
                    'msg_next' => 'Request for TAF Extension endorsement',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 1,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Verified',
                    'status_description' => 'Verified',
//                'assign_next_user' => 0,
                ),
            13 =>
                array (
                    'id' => 14,
                    'level' => '3',
                    'unit_id' => '6',
                    'designation_id' => '9',
                    'description' => 'Endorse TAF Extension',
                    'msg_next' => 'Request for TAF Extension Approval',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Endorsed',
                    'status_description' => 'Endorsed',
//                'assign_next_user' => 0,
                ),
            14 =>
                array (
                    'id' => 15,
                    'level' => '4',
                    'unit_id' => '31',
                    'designation_id' => '61',
                    'description' => 'Approve TAF Extension',
                    'msg_next' => 'Request for TAF Extension inspection',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 1,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Approved',
                    'status_description' => 'Approved',
//                'assign_next_user' => 0,
                ),
            15 =>
                array (
                    'id' => 16,
                    'level' => '5',
                    'unit_id' => '1',
                    'designation_id' => '1',
                    'description' => 'Inspect TAF Extension',
                    'msg_next' => 'Request for TAF Extension payment',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 0,
                    'action_description' => 'Inspected',
                    'status_description' => 'Inspected',
//                'assign_next_user' => 0,
                ),
            16 =>
                array (
                    'id' => 17,
                    'level' => '6',
                    'unit_id' => '1',
                    'designation_id' => '2',
                    'description' => 'Pay TAF Extension',
                    'msg_next' => 'Request for TAF Extension payment',
                    'wf_module_id' => 3,
                    'active' => '1',
                    'allow_rejection' => 1,
                    'allow_repeat_participate' => 0,
                    'created_at' => '2020-11-19 11:20:42',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                    'is_approval' => 0,
                    'has_next_start_optional' => 0,
                    'is_optional' => 0,
                    'can_close' => 1,
                    'action_description' => 'Paid',
                    'status_description' => 'Paid',
//                'assign_next_user' => 0,
                ),
            /*END TAF EXTENSION*/


                        /*START COV AND CEC MONTHLY PAYMENT*/
                        17 =>
                        array (
                            'id' => 18,
                            'level' => '1',
                            'unit_id' => 33,
                            'designation_id' => 63,
                            'description' => 'Initiate Payment ',
                            'msg_next' => 'Request Review And Modification',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 0,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 0,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 0,
                            'action_description' => 'Initiated',
                            'status_description' => 'Initiated',
                        ),
                    18 =>
                        array (
                            'id' => 19,
                            'level' => '2',
                            'unit_id' => '19',
                            'designation_id' => '40',
                            'description' => 'Review And Modification',
                            'msg_next' => 'Request for Verification',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 1,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 0,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 0,
                            'action_description' => 'Reviewed and modified',
                            'status_description' => 'Reviewed and modified',
        //                'assign_next_user' => 0,
                        ),
                    19 =>
                        array (
                            'id' => 20,
                            'level' => '3',
                            'unit_id' => '26',
                            'designation_id' => '51',
                            'description' => 'Verify',
                            'msg_next' => 'Request for Payment Endorsement',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 0,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 0,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 0,
                            'action_description' => 'Verified',
                            'status_description' => 'Verified',
        //                'assign_next_user' => 0,
                        ),
                    20 =>
                        array (
                            'id' => 21,
                            'level' => '4',
                            'unit_id' => '6',
                            'designation_id' => '9',
                            'description' => 'Endorse',
                            'msg_next' => 'Request for Payment Approval',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 0,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 1,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 0,
                            'action_description' => 'Endorsed',
                            'status_description' => 'Endorsed',
        //                'assign_next_user' => 0,
                        ),
                    21 =>
                        array (
                            'id' => 22,
                            'level' => '5',
                            'unit_id' => '31',
                            'designation_id' => '61',
                            'description' => 'Payment Approval',
                            'msg_next' => 'Request for Completed',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 0,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 1,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 0,
                            'action_description' => 'Approved',
                            'status_description' => 'Approved',
        //                'assign_next_user' => 0,
                        ),
                    22 =>
                        array (
                            'id' => 23,
                            'level' => '6',
                            'unit_id' => '1',
                            'designation_id' => '2',
                            'description' => 'Payment Completed',
                            'msg_next' => 'Payment Completion',
                            'wf_module_id' => 4,
                            'active' => '1',
                            'allow_rejection' => 1,
                            'allow_repeat_participate' => 0,
                            'created_at' => '2021-03-17 11:49:11',
                            'updated_at' => NULL,
                            'deleted_at' => NULL,
                            'is_approval' => 0,
                            'has_next_start_optional' => 0,
                            'is_optional' => 0,
                            'can_close' => 1,
                            'action_description' => 'Paid',
                            'status_description' => 'Paid',
        //                'assign_next_user' => 0,
                        ),
                    /*END COV AND CEC MONTHLY PAYMENT*/

                    /*START LEAVE APPLICATION*/
23 =>
array(
    'id' => 24,
    'level' => '1',
    'unit_id' => 33,
    'designation_id' => 63,
    'description' => 'Request LEAVE',
    'msg_next' => 'Request leave verification',
    'wf_module_id' => 5,
    'active' => '1',
    'allow_rejection' => 1,
    'allow_repeat_participate' => 0,
    'created_at' => '2021-06-15 14:24:00',
    'updated_at' => NULL,
    'deleted_at' => NULL,
    'is_approval' => 0,
    'has_next_start_optional' => 0,
    'is_optional' => 0,
    'can_close' => 0,
    'action_description' => 'Requested',
    'status_description' => 'Requested',
//                  'assign_next_user' => 0,
),
24 =>
array(
    'id' => 25,
    'level' => '2',
    'unit_id' => 32,
    'designation_id' => 62,
    'description' => 'Verify LEAVE',
    'msg_next' => 'Request for recommendation',
    'wf_module_id' => 5,
    'active' => '1',
    'allow_rejection' => 1,
    'allow_repeat_participate' => 1,
    'created_at' => '2021-06-15 14:25:00',
    'updated_at' => NULL,
    'deleted_at' => NULL,
    'is_approval' => 0,
    'has_next_start_optional' => 0,
    'is_optional' => 0,
    'can_close' => 0,
    'action_description' => 'Verified',
    'status_description' => 'Verified',
//                  'assign_next_user' => 0,
),
25 =>
array(
    'id' => 26,
    'level' => '3',
    'unit_id' => 22,
    'designation_id' => 65,
    'description' => 'Recommend LEAVE',
    'msg_next' => 'Request for Approval',
    'wf_module_id' => 5,
    'active' => '1',
    'allow_rejection' => 1,
    'allow_repeat_participate' => 1,
    'created_at' => '2021-06-15 14:26:00',
    'updated_at' => NULL,
    'deleted_at' => NULL,
    'is_approval' => 0,
    'has_next_start_optional' => 0,
    'is_optional' => 0,
    'can_close' => 0,
    'action_description' => 'Recommended',
    'status_description' => 'Recommended',
//                  'assign_next_user' => 0,
),
26 =>
array(
    'id' => 27,
    'level' => '4',
    'unit_id' => 6,
    'designation_id' => 9,
    'description' => 'Approve LEAVE',
    'msg_next' => 'Request for Approval',
    'wf_module_id' => 5,
    'active' => '1',
    'allow_rejection' => 1,
    'allow_repeat_participate' => 1,
    'created_at' => '2021-06-15 14:44:00',
    'updated_at' => NULL,
    'deleted_at' => NULL,
    'is_approval' => 0,
    'has_next_start_optional' => 0,
    'is_optional' => 0,
    'can_close' => 1,
    'action_description' => 'Approved',
    'status_description' => 'Approved',
//                  'assign_next_user' => 0,
),
/*END LEAVE APPLICATION*/
        
        
                    

        ));

        $this->enableForeignKeys('wf_definitions');

    }
}
