@extends('layouts.app')
@section('content')
        @csrf
        @include('HumanResource.Interview.header.main')
        @include('HumanResource.Interview.panelist.show')
        @include('HumanResource.Interview.question.show')
        @include('HumanResource.Interview.applicant.invited')  
        @if(count($interviewApplicants))
            @include('HumanResource.Interview.applicant.shortlisted')   
        @endif
        @include('HumanResource.Interview.applicant.confirmed')   
@endsection